######################################################################
# Automatically generated by qmake (3.1) Tue Mar 3 10:11:01 2026
######################################################################

TEMPLATE = app
TARGET = tagviewer
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_UP_TO=0x060000 # disables all APIs deprecated in Qt 6.0.0 and earlier

# Input
HEADERS += mainwindow.h \
           pixmaplabel.h \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/tagviewer_autogen/include/ui_mainwindow.h \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/adl_serializer.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/byte_container_with_subtype.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/json.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/json_fwd.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/ordered_map.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/single_include/nlohmann/json.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/single_include/nlohmann/json_fwd.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/adl_serializer.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/byte_container_with_subtype.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/json.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/json_fwd.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/ordered_map.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/single_include/nlohmann/json.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/single_include/nlohmann/json_fwd.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/abi_macros.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/exceptions.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/hash.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/json_custom_base_class.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/json_pointer.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/json_ref.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/macro_scope.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/macro_unscope.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/string_concat.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/string_escape.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/string_utils.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/value_t.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/abi_macros.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/exceptions.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/hash.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/json_custom_base_class.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/json_pointer.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/json_ref.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/macro_scope.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/macro_unscope.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/string_concat.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/string_escape.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/string_utils.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/value_t.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/conversions/from_json.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/conversions/to_chars.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/conversions/to_json.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/input/binary_reader.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/input/input_adapters.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/input/json_sax.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/input/lexer.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/input/parser.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/input/position_t.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/iterators/internal_iterator.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/iterators/iter_impl.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/iterators/iteration_proxy.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/iterators/iterator_traits.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/iterators/json_reverse_iterator.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/iterators/primitive_iterator.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/meta/cpp_future.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/meta/detected.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/meta/identity_tag.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/meta/is_sax.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/meta/std_fs.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/meta/type_traits.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/meta/void_t.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/output/binary_writer.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/output/output_adapters.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/output/serializer.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/thirdparty/hedley/hedley.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/thirdparty/hedley/hedley_undef.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/conversions/from_json.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/conversions/to_chars.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/conversions/to_json.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/input/binary_reader.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/input/input_adapters.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/input/json_sax.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/input/lexer.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/input/parser.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/input/position_t.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/iterators/internal_iterator.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/iterators/iter_impl.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/iterators/iteration_proxy.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/iterators/iterator_traits.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/iterators/json_reverse_iterator.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/iterators/primitive_iterator.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/meta/cpp_future.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/meta/detected.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/meta/identity_tag.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/meta/is_sax.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/meta/std_fs.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/meta/type_traits.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/meta/void_t.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/output/binary_writer.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/output/output_adapters.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/output/serializer.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/thirdparty/hedley/hedley.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/thirdparty/hedley/hedley_undef.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/meta/call_std/begin.hpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/_deps/json-src/include/nlohmann/detail/meta/call_std/end.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/meta/call_std/begin.hpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/_deps/json-src/include/nlohmann/detail/meta/call_std/end.hpp \
           /build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/tagviewer_autogen/include/ui_mainwindow.h \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/tagviewer_autogen/EWIEGA46WW/moc_mainwindow.cpp
FORMS += mainwindow.ui
SOURCES += main.cpp \
           mainwindow.cpp \
           pixmaplabel.cpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/tagviewer_autogen/mocs_compilation.cpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/tagviewer_autogen/EWIEGA46WW/qrc_icons.cpp \
           build/Clone_of_Desktop_Qt_6_10_0_MSVC2022_64bit-Debug/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           build/Desktop_Qt_6_10_0_llvm_mingw_64_bit-Debug/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp
RESOURCES += icons.qrc
